const CONFIG = {
  MAX_COMPARE_PRODUCT: 2,
  MAX_SALE_PRODUCT: 99,
  MIN_SALE_PRODUCT: 1,
  MAX_SAVE_PRODUCT_RECENT_VIEW: 10,
  LIMIT_SHOW_PRODUCT_LIST: 20,
  ONE_HUN: 1000000,
  KEY_ACTIVE_OPTIONS: "variant",
  HOTLINE: "0566.44.77.99",
  DOMAIN: process.env.DOMAIN,
};

export default CONFIG;
